name: Cypress Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Install dependencies
      run: npm install
      
    - name: Install cypress latest version
      run: npm install cypress@latest --save-dev

    - name: Run Cypress desktop
      run: npm run desktop
      
    - name: Run Cypress mobile
      run: npm run mobile
