name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Install dependencies
      run: npm install
      
    - name: Install cypress latest version
      run: npm install cypress@latest --save-dev

    - name: Run Cypress desktop terminal
      run: npm run desktop
      
    - name: Run Cypress mobile terminal
      run: npm run mobile
      
    - name: Run Cypress desktop browser
      run: npm run desktop-browser
      
    - name: Run Cypress mobile browser
      run: npm run mobile-browser
