name: run unit tests of feature branches

on:
  push:
    branches:
      'v*'
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v.3.3.0

      - name: run unit test
        run: mvn test
