name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Install dependencies
      run: npm install
      
    - name: Install cypress latest version
      run: npm install cypress@latest --save-dev

    - name: Run Cypress tests
      run: npm run desktop
